{{- if .Values.agent }}
{{- $ReleaseNamespace := .Release.Namespace -}}
{{- with .Values.agent }}
{{- if .config }}
{{- if not .config.name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ $ReleaseNamespace }}
data:
  config.json: |
  {{- with .config }}
  {{- toJson . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
