{{- if .Values.agent.rbac.enabled -}}
{{- $ReleaseName := .Release.Name -}}
{{- $ReleaseNamespace := .Release.Namespace -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $ReleaseNamespace }}-{{ $ReleaseName }}
  labels:
    {{- with .Values.agent.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.agent.serviceAccount.name }}
  namespace: {{ $ReleaseNamespace }}
{{- end }}
