apiVersion: v2
name: nesis
description: A Helm chart for Nesis, Your Enterprise Knowledge Partner
type: application
version: "0.1.8"
appVersion: "0.1.3"

dependencies:
- name: postgresql
  version: 12.12.7
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled

- name: memcached
  version: 6.12.1
  repository: https://charts.bitnami.com/bitnami
  condition: memcached.enabled

- name: minio
  version: 14.2.1
  repository: https://charts.bitnami.com/bitnami
  condition: minio.enabled
