api:
  env:
    # - name: LOG_LEVEL
    #   value: DEBUG
    - name: NESIS_ADMIN_EMAIL
      value: test@domain.com
    - name: NESIS_ADMIN_PASSWORD
      value: password
    - name: NESIS_RAG_EMBEDDING_MODE
      value: local
    - name: NESIS_RAG_EMBEDDING_DIMENSIONS
      value: "384"

rag:
  enabled: true
  podSecurityContext:
    fsGroup: 2002
  securityContext:
    runAsUser: 1001
    runAsGroup: 2002

  persistence:
    enabled: true
    size: 10Gi
  
  extraEnv:
    - name: OPENAI_API_KEY
      value: sk-
    # - name: OPENAI_API_BASE
    #   value: http://
  config: null
