apiVersion: v2
name: cloud-agent
description: A Helm chart for Ametnes System
type: application
version: 0.1.4
appVersion: 1.16.0
dependencies:
- name: memcached
  version: 5.15.8
  repository: https://charts.bitnami.com/bitnami
