name: Nesis Test Charts

on:
  push:
    paths:
      - charts/nesis/**/*.yml
      - charts/nesis/**/*.yaml
      - charts/nesis/templates/**
    branches:
      - main

env:
  HELM_VERSION: 3.6.3

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: "${{ env.HELM_VERSION }}"

      - name: Add helm repos
        run: |
          helm repo add bitnami https://bitnami.github.io/bitnami-charts
          helm repo update

      - name: Install unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Run nesis unit tests
        run: helm unittest ./charts/nesis
