name: Agent Release Charts

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # - name: Add helm
      #   run: |
      #     helm repo add memchached charts/agent/charts/memcached
      #     helm repo add velero charts/agent/charts/velero
      #     helm repo add nfs-server-provisioner charts/agent/charts/nfs-server-provisioner

      - name: Update Helm repositories
        run: helm dependency update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
